@@startuml JCTree-model
hide members
skinparam backgroundcolor black
skinparam classBackgroundColor gray
skinparam ClassBorderColor white
skinparam ClassFontColor white

abstract class JCTree implements Tree, Cloneable

interface StatementTree extends Tree
abstract class JCStatement extends JCTree implements StatementTree
abstract class JCExpression extends JCTree implements ExpressionTree

class JCCompilationUnit extends JCTree implements CompilationUnitTree 


class JCClassDecl extends JCStatement implements ClassTree{
    + JCModifiers mods;
    /** the name of the class */
    + Name name;
    /** formal class parameters */
    + List<JCTypeParameter> typarams;
    /** the classes this class extends */
    + JCExpression extending;
    /** the interfaces implemented by this class */
    + List<JCExpression> implementing;
    /** all variables and methods defined in this class */
    + List<JCTree> defs;
    /** the symbol */
    + ClassSymbol sym;
}

interface ClassTree extends StatementTree

class JCAssign extends JCExpression
class JCIdent extends JCExpression
class JCBlock extends JCStatement


@@enduml